### ISSUE TITLE
prepare-alignments.py AttributeError for quartet alignment

### ISSUE THREAD

**Issue by nathanweeks** [mailund/IMCoalHMM#4]
My attempt at fixing the prepare-alignments.py missing-module issue (https://github.com/mailund/IMCoalHMM/commit/d3b1916711cbbc1946e47c4c8a41b17dd46c084d) was incomplete---sorry!
A colleague subsequently reported this AttributeError:
```
Loading data... done
Assuming quartet alignment between 'min1', 'min2', 'bic1', and 'bic2'
Writing file readable by ziphmm to './IMAcoal3'... done
ZipHMM is pre-processing...
Traceback (most recent call last):
  File "/usr/local/bin/prepare-alignments.py", line 213, in <module>
    main()
  File "/usr/local/bin/prepare-alignments.py", line 202, in main
    f = Forwarder.fromSequence(seqFilename=outname, alphabetSize=9, minNoEvals=500)
AttributeError: class Forwarder has no attribute 'fromSequence'
```
Indeed, the code is attempting to call a non-existent attribute. Is this fixable?

**Comment by biozhangzhou** [comment]
Did you fixed this issue?
